#Amazon India Sales Analytics (2015–2025)
##Objective
To analyze 10+ years of Amazon India sales data to understand:

* Sales trends over time
* Customer behavior
* Festival impact on revenue
* Category-wise performance

##Import Libraries

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

##Merge the Dataset

In [2]:
!pip install -q gdown

In [3]:
import gdown

folder_url = "https://drive.google.com/drive/folders/1ZHB4x8nZHuXmyDlwujWtbOaxiMHWf-3-"

gdown.download_folder(folder_url, quiet=False)

Retrieving folder contents

Processing file 15rXSetBXP2JBwilAPKSlCGwxs4uQtq6_ amazon_india_2015.csv
Processing file 1n7n61Uiz4NGYjCUblNLO9fV3MyMJeXS- amazon_india_2016.csv
Processing file 1yib7orIHGhlQL4mZVRcuesXvJDTUYQNc amazon_india_2017.csv
Processing file 1OufINNm9eDhNSfHuxAx68xS_LadxAO7f amazon_india_2018.csv
Processing file 1ktjfxU1iH53FsNscXIIwSiBbuIFyb1lm amazon_india_2019.csv
Processing file 1MAqWZinT7fhtw1VqR0SG4skSYK6d7KYA amazon_india_2020.csv
Processing file 1g7I2Y42CdvmfbMQpN-TXGCmdl4dqVHOm amazon_india_2021.csv
Processing file 1SKFVVeSG8s3NIfIGNKdtZ0i9KOys69Hk amazon_india_2022.csv
Processing file 1FVkd0ZYyWmz7R5tuDUa9D_KE3Mfa10WE amazon_india_2023.csv
Processing file 1CteSeaY-y_mEiHIf7BITERd5NMy6Z_yb amazon_india_2024.csv
Processing file 1svbwjDRzacKN-BQB0H43rSp0XHbCR_bY amazon_india_2025.csv
Processing file 1axt6hcyC99pXgd1kA99pZewg5Tz9sR2N amazon_india_products_catalog.csv

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=15rXSetBXP2JBwilAPKSlCGwxs4uQtq6_
To: /content/Dataset/amazon_india_2015.csv
100%|██████████| 9.12M/9.12M [00:00<00:00, 38.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1n7n61Uiz4NGYjCUblNLO9fV3MyMJeXS-
To: /content/Dataset/amazon_india_2016.csv
100%|██████████| 15.2M/15.2M [00:00<00:00, 56.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1yib7orIHGhlQL4mZVRcuesXvJDTUYQNc
To: /content/Dataset/amazon_india_2017.csv
100%|██████████| 21.2M/21.2M [00:00<00:00, 68.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1OufINNm9eDhNSfHuxAx68xS_LadxAO7f
To: /content/Dataset/amazon_india_2018.csv
100%|██████████| 27.3M/27.3M [00:00<00:00, 56.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ktjfxU1iH53FsNscXIIwSiBbuIFyb1lm
To: /content/Dataset/amazon_india_2019.csv
100%|██████████| 33.4M/33.4M [00:00<00:00, 74.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1MAqWZinT7fhtw1VqR0SG4skSYK6d7KYA
To: /content/Dataset/amazon_india_2020.csv
100%|██████████| 39.5M/39.5M [00:00<00:00, 108MB/s]
Downloading...
From: https://drive.google.com/uc?id=1g7I2Y42CdvmfbMQpN-TXGCmdl4dqVHOm
To: /content/Dataset/amazon_india_2021.csv
100%|██████████| 37.9M/37.9M [00:00<00:00, 75.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1SKFVVeSG8s3NIfIGNKdtZ0i9KOys69Hk
To: /content/Dataset/amazon_india_2022.csv
100%|██████████| 36.4M/36.4M [00:00<00:00, 58.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1FVkd0ZYyWmz7R5tuDUa9D_KE3Mfa10WE
To: /content/Dataset/amazon_india_2023.csv
100%|██████████| 34.8M/34.8M [00:00<00:00, 83.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1CteSeaY-y_mEiHIf7BITERd5NMy6Z_yb
To: /content/Dataset/amazon_india_2024.csv
100%|██████████| 33.3M/33.3M [00:00<00:00, 69.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1svbwjDRzacKN-BQB0H43rSp0XHbCR_bY
To: /content/Dataset/amazon_india_2025.csv
100%|██████████| 21.1M/21.1M [00:00<00:00, 71.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1axt6hcyC99pXgd1kA99pZewg5Tz9sR2N
To: /content/Dataset/amazon_india_products_catalog.csv
100%|██████████| 218k/218k [00:00<00:00, 62.1MB/s]
Download completed

['/content/Dataset/amazon_india_2015.csv',
 '/content/Dataset/amazon_india_2016.csv',
 '/content/Dataset/amazon_india_2017.csv',
 '/content/Dataset/amazon_india_2018.csv',
 '/content/Dataset/amazon_india_2019.csv',
 '/content/Dataset/amazon_india_2020.csv',
 '/content/Dataset/amazon_india_2021.csv',
 '/content/Dataset/amazon_india_2022.csv',
 '/content/Dataset/amazon_india_2023.csv',
 '/content/Dataset/amazon_india_2024.csv',
 '/content/Dataset/amazon_india_2025.csv',
 '/content/Dataset/amazon_india_products_catalog.csv']

In [4]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        print(os.path.join(root, file))

./.config/gce
./.config/.last_update_check.json
./.config/default_configs.db
./.config/active_config
./.config/.last_opt_in_prompt.yaml
./.config/.last_survey_prompt.yaml
./.config/config_sentinel
./.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
./.config/configurations/config_default
./.config/logs/2026.06.04/13.32.38.346437.log
./.config/logs/2026.06.04/13.32.02.654775.log
./.config/logs/2026.06.04/13.32.18.735754.log
./.config/logs/2026.06.04/13.32.39.344962.log
./.config/logs/2026.06.04/13.31.42.499627.log
./.config/logs/2026.06.04/13.32.21.210570.log
./Dataset/amazon_india_2019.csv
./Dataset/amazon_india_2023.csv
./Dataset/amazon_india_2016.csv
./Dataset/amazon_india_2015.csv
./Dataset/amazon_india_2022.csv
./Dataset/amazon_india_2025.csv
./Dataset/amazon_india_2021.csv
./Dataset/amazon_india_2017.csv
./Dataset/amazon_india_products_catalog.csv
./Dataset/amazon_india_2024.csv
./Dataset/amazon_india_2020.csv
./Dataset/amazon_india_2018.csv

In [5]:
import pandas as pd
import glob

csv_files = glob.glob("**/*.csv", recursive=True)

print("CSV Files Found:")
for f in csv_files:
    print(f)

dfs = [pd.read_csv(f) for f in csv_files]

merged_df = pd.concat(dfs, ignore_index=True)

print("Merged Shape:", merged_df.shape)

merged_df.head()

CSV Files Found:
Dataset/amazon_india_2019.csv
Dataset/amazon_india_2023.csv
Dataset/amazon_india_2016.csv
Dataset/amazon_india_2015.csv
Dataset/amazon_india_2022.csv
Dataset/amazon_india_2025.csv
Dataset/amazon_india_2021.csv
Dataset/amazon_india_2017.csv
Dataset/amazon_india_products_catalog.csv
Dataset/amazon_india_2024.csv
Dataset/amazon_india_2020.csv
Dataset/amazon_india_2018.csv
Merged Shape: (1129613, 39)

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating,base_price_2015,weight_kg,rating,launch_year,model
0,TXN_2019_00000001,2019-01-05,CUST_2019_00037860,PROD_001930,Fitbit Sports Watch Premium,Electronics,Smart Watch,Fitbit,29122.09,0.00,...,2019.0,1.0,0.06,True,3.4,NaN,NaN,NaN,NaN,NaN
1,TXN_2019_00000002,2019-01-09,CUST_2019_00002481,PROD_001683,Apple Mi Pad 8GB RAM Silver,Electronics,Tablets,Apple,66396.45,0.00,...,2019.0,1.0,0.40,True,4.5,NaN,NaN,NaN,NaN,NaN
2,TXN_2019_00000003,01/02/2019,CUST_2018_00031347,PROD_000460,Oppo F9 64GB Black,Electronics,Smartphones,Oppo,29966.28,0.00,...,2019.0,1.0,0.16,True,3.3,NaN,NaN,NaN,NaN,NaN
3,TXN_2019_00000004,2019-01-22,CUST_2019_00024783,PROD_000633,Oppo Reno 64GB White,Electronics,Smartphones,Oppo,34225.21,19.68,...,2019.0,1.0,0.20,True,3.3,NaN,NaN,NaN,NaN,NaN
4,TXN_2019_00000005,2019-01-31,CUST_2019_00018471,PROD_000571,Xiaomi Mi A3 256GB Blue,Electronics,Smartphones,Xiaomi,27092.49,0.00,...,2019.0,1.0,0.25,True,4.5,NaN,NaN,NaN,NaN,NaN

In [6]:
import pandas as pd
import os

folder = "/content/Dataset"

for year in range(2015, 2026):
    df = pd.read_csv(os.path.join(folder, f"amazon_india_{year}.csv"))
    print(year, df.shape)

2015 (33165, 34)
2016 (55275, 34)
2017 (77385, 34)
2018 (99495, 34)
2019 (121605, 34)
2020 (143715, 34)
2021 (138187, 34)
2022 (132660, 34)
2023 (127132, 34)
2024 (121605, 34)
2025 (77385, 34)

In [7]:
import pandas as pd
import os

folder = "/content/Dataset"

dfs = []

for year in range(2015, 2026):
    file = os.path.join(folder, f"amazon_india_{year}.csv")
    df = pd.read_csv(file)
    dfs.append(df)

amazon_data = pd.concat(dfs, ignore_index=True)

print("Merged Shape:", amazon_data.shape)

Merged Shape: (1127609, 34)

In [15]:
amazon_data.to_csv(
    "/content/amazon_india_completes_2015_2025.csv",
    index=False
)

print("Saved successfully")

Saved successfully

##Loading the Dataset

In [16]:
df = pd.read_csv('amazon_india_completes_2015_2025.csv')
df.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,NaN,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,"21,947.26",0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,FALSE,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1

##Dataset Overview

In [17]:
df.shape

(1127609, 34)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127609 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1127609 non-null  object
 1   order_date              1127609 non-null  object
 2   customer_id             1127609 non-null  object
 3   product_id              1127609 non-null  object
 4   product_name            1127609 non-null  object
 5   category                1127609 non-null  object
 6   subcategory             1127609 non-null  object
 7   brand                   1127609 non-null  object
 8   original_price_inr      1127609 non-null  object
 9   discount_percent        1127609 non-null  float64
 10  discounted_price_inr    1127609 non-null  float64
 11  quantity                1127609 non-null  int64
 12  subtotal_inr            1127609 non-null  float64
 13  delivery_charges        1037408 non-null  float64
 14  final_amount_inr        1127609 non-null  float64
 15  customer_city           1127609 non-null  object
 16  customer_state          1127609 non-null  object
 17  customer_tier           1127609 non-null  object
 18  customer_spending_tier  1127609 non-null  object
 19  customer_age_group      992294 non-null   object
 20  payment_method          1127609 non-null  object
 21  delivery_days           1127609 non-null  object
 22  delivery_type           1127609 non-null  object
 23  is_prime_member         1127609 non-null  object
 24  is_festival_sale        1127609 non-null  object
 25  festival_name           349873 non-null   object
 26  customer_rating         785913 non-null   object
 27  return_status           1127609 non-null  object
 28  order_month             1127609 non-null  int64
 29  order_year              1127609 non-null  int64
 30  order_quarter           1127609 non-null  int64
 31  product_weight_kg       1127609 non-null  float64
 32  is_prime_eligible       1127609 non-null  object
 33  product_rating          1127609 non-null  float64
dtypes: float64(7), int64(4), object(23)
memory usage: 292.5+ MB

In [19]:
df.isnull().sum()

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           90201
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        135315
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             777736
customer_rating           341696
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64

In [20]:
df.nunique()

transaction_id            1127609
order_date                  14414
customer_id                354969
product_id                   2004
product_name                 1974
category                        5
subcategory                     6
brand                          29
original_price_inr          46185
discount_percent             6502
discounted_price_inr       605861
quantity                        3
subtotal_inr               629180
delivery_charges                2
final_amount_inr           629180
customer_city                  50
customer_state                 15
customer_tier                   4
customer_spending_tier          3
customer_age_group              5
payment_method                  7
delivery_days                  13
delivery_type                   3
is_prime_member                 8
is_festival_sale                8
festival_name                   8
customer_rating                21
return_status                   3
order_month                    12
order_year                     11
order_quarter                   4
product_weight_kg             206
is_prime_eligible               8
product_rating                 19
dtype: int64

##Data Cleaning

###Data Types Handling

In [21]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    errors='coerce',
    dayfirst=True
)

In [22]:
df['original_price_inr'] = pd.to_numeric(df['original_price_inr'], errors='coerce')
df['customer_rating'] = pd.to_numeric(df['customer_rating'], errors='coerce')

In [23]:
df['delivery_days'] = pd.to_numeric(df['delivery_days'], errors='coerce')

In [24]:
bool_map = {
    'true': True, 'false': False,
    '1': True, '0': False,
    'yes': True, 'no': False
}

for col in ['is_prime_member', 'is_festival_sale', 'is_prime_eligible']:
    df[col] = (
        df[col]
        .astype(str)
        .str.lower()
        .map(bool_map)
    )

In [25]:
df.dtypes

transaction_id                    object
order_date                datetime64[ns]
customer_id                       object
product_id                        object
product_name                      object
category                          object
subcategory                       object
brand                             object
original_price_inr               float64
discount_percent                 float64
discounted_price_inr             float64
quantity                           int64
subtotal_inr                     float64
delivery_charges                 float64
final_amount_inr                 float64
customer_city                     object
customer_state                    object
customer_tier                     object
customer_spending_tier            object
customer_age_group                object
payment_method                    object
delivery_days                    float64
delivery_type                     object
is_prime_member                     bool
is_festival_sale                    bool
festival_name                     object
customer_rating                  float64
return_status                     object
order_month                        int64
order_year                         int64
order_quarter                      int64
product_weight_kg                float64
is_prime_eligible                   bool
product_rating                   float64
dtype: object

###Null Values Handling

In [26]:
df.isnull().sum()

transaction_id                 0
order_date                108256
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr        101569
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           90201
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        135315
payment_method                 0
delivery_days              11320
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             777736
customer_rating           398240
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64

In [27]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce', dayfirst=True)

df = df.dropna(subset=['order_date'])   #drop invalid dates for time-series analysis

In [28]:
df['original_price_inr'] = (
    df['original_price_inr']
    .astype(str)
    .str.extract(r'(\d[\d,]*\.?\d*)')[0]
    .str.replace(',', '', regex=True)
)

df['original_price_inr'] = pd.to_numeric(df['original_price_inr'], errors='coerce')  #original_price_inr

In [29]:
df['original_price_inr'] = df['original_price_inr'].fillna(df['original_price_inr'].median())

In [30]:
df['delivery_charges'] = df['delivery_charges'].fillna(df['delivery_charges'].median())  #delivery_charges

In [31]:
df['customer_age_group'] = df['customer_age_group'].fillna("Unknown")

In [32]:
df['delivery_days'] = pd.to_numeric(df['delivery_days'], errors='coerce')
df['delivery_days'] = df['delivery_days'].fillna(df['delivery_days'].median())

In [33]:
df['festival_name'] = df['festival_name'].fillna("No Festival")

In [34]:
df['customer_rating'] = pd.to_numeric(df['customer_rating'], errors='coerce')

df['customer_rating'] = df.groupby('customer_tier')['customer_rating'].transform(
    lambda x: x.fillna(x.mean())
)

df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].mean())

In [35]:
df.isnull().sum()

transaction_id            0
order_date                0
customer_id               0
product_id                0
product_name              0
category                  0
subcategory               0
brand                     0
original_price_inr        0
discount_percent          0
discounted_price_inr      0
quantity                  0
subtotal_inr              0
delivery_charges          0
final_amount_inr          0
customer_city             0
customer_state            0
customer_tier             0
customer_spending_tier    0
customer_age_group        0
payment_method            0
delivery_days             0
delivery_type             0
is_prime_member           0
is_festival_sale          0
festival_name             0
customer_rating           0
return_status             0
order_month               0
order_year                0
order_quarter             0
product_weight_kg         0
is_prime_eligible         0
product_rating            0
dtype: int64

###Data Inconsistency Handling

####1)Standardize Boolean Columns

In [36]:
bool_cols = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']

for col in bool_cols:
    df[col] = (
        df[col].astype(str).str.strip().str.lower()
        .replace({
            'true': True, 'false': False,
            '1': True, '0': False,
            'yes': True, 'no': False
        })
    )

####2)Fix Category Column (case + spelling issues)

In [37]:
df['category'] = df['category'].str.strip().str.lower()

df['category'] = df['category'].replace({
    'electronic': 'electronics',
    'electronicss': 'electronics',
    'electronics & accessories': 'electronics'
})

####3)Clean Customer City Names

In [38]:
df['customer_city'] = df['customer_city'].str.strip().str.lower()

city_map = {
    'bombay': 'mumbai',
    'mumba': 'mumbai',
    'bangalore': 'bengaluru',
    'banglore': 'bengaluru',
    'calcutta': 'kolkata',
    'madras': 'chennai',
    'new delhi': 'delhi',
    'delhi ncr': 'delhi'
}

df['customer_city'] = df['customer_city'].replace(city_map).str.title()

####4)Fix Customer Rating Format

In [39]:
import re

df['customer_rating'] = (
    df['customer_rating']
    .astype(str)
    .str.extract(r'(\d+\.?\d*)')[0]
)

df['customer_rating'] = pd.to_numeric(df['customer_rating'], errors='coerce')

####5)Clean Delivery Days

In [40]:
import numpy as np
import pandas as pd
import re

def clean_delivery(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().lower()

    # empty string check
    if x == "" or x == "nan":
        return np.nan

    # special cases
    if "same" in x or "express" in x:
        return 0

    # range case (1-2 days)
    match = re.match(r'(\d+)\s*-\s*(\d+)', x)
    if match:
        a, b = match.groups()
        return (float(a) + float(b)) / 2

    # extract single number
    num = re.search(r'\d+', x)
    if num:
        return float(num.group())

    return np.nan

df['delivery_days'] = df['delivery_days'].apply(clean_delivery)

In [41]:
report = {
    "missing_values": df.isnull().sum().sum(),
    "duplicate_rows": df.duplicated().sum(),
    "object_columns": len(df.select_dtypes(include='object').columns),
    "numeric_columns": len(df.select_dtypes(include='number').columns)
}

report

{'missing_values': np.int64(0),
 'duplicate_rows': np.int64(0),
 'object_columns': 16,
 'numeric_columns': 14}

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1019353 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1019353 non-null  object
 1   order_date              1019353 non-null  datetime64[ns]
 2   customer_id             1019353 non-null  object
 3   product_id              1019353 non-null  object
 4   product_name            1019353 non-null  object
 5   category                1019353 non-null  object
 6   subcategory             1019353 non-null  object
 7   brand                   1019353 non-null  object
 8   original_price_inr      1019353 non-null  float64
 9   discount_percent        1019353 non-null  float64
 10  discounted_price_inr    1019353 non-null  float64
 11  quantity                1019353 non-null  int64
 12  subtotal_inr            1019353 non-null  float64
 13  delivery_charges        1019353 non-null  float64
 14  final_amount_inr        1019353 non-null  float64
 15  customer_city           1019353 non-null  object
 16  customer_state          1019353 non-null  object
 17  customer_tier           1019353 non-null  object
 18  customer_spending_tier  1019353 non-null  object
 19  customer_age_group      1019353 non-null  object
 20  payment_method          1019353 non-null  object
 21  delivery_days           1019353 non-null  float64
 22  delivery_type           1019353 non-null  object
 23  is_prime_member         1019353 non-null  bool
 24  is_festival_sale        1019353 non-null  bool
 25  festival_name           1019353 non-null  object
 26  customer_rating         1019353 non-null  float64
 27  return_status           1019353 non-null  object
 28  order_month             1019353 non-null  int64
 29  order_year              1019353 non-null  int64
 30  order_quarter           1019353 non-null  int64
 31  product_weight_kg       1019353 non-null  float64
 32  is_prime_eligible       1019353 non-null  bool
 33  product_rating          1019353 non-null  float64
dtypes: bool(3), datetime64[ns](1), float64(10), int64(4), object(16)
memory usage: 251.8+ MB

In [43]:
obj_cols = df.select_dtypes(include='object').columns

for col in obj_cols:
    print("\n", col)
    print(df[col].unique()[:10])

 transaction_id
['TXN_2015_00000001' 'TXN_2015_00000002' 'TXN_2015_00000003'
 'TXN_2015_00000004' 'TXN_2015_00000005' 'TXN_2015_00000006'
 'TXN_2015_00000007' 'TXN_2015_00000008' 'TXN_2015_00000009'
 'TXN_2015_00000010']

 customer_id
['CUST_2015_00003884' 'CUST_2015_00011709' 'CUST_2015_00004782'
 'CUST_2015_00008105' 'CUST_2015_00002955' 'CUST_2015_00006757'
 'CUST_2015_00008012' 'CUST_2015_00011809' 'CUST_2015_00006429'
 'CUST_2015_00001829']

 product_id
['PROD_000021' 'PROD_000055' 'PROD_000039' 'PROD_000085' 'PROD_001665'
 'PROD_000031' 'PROD_000048' 'PROD_000082' 'PROD_000037' 'PROD_001693']

 product_name
['Samsung Galaxy S6 16GB Black' 'OnePlus OnePlus 2 16GB White'
 'Samsung Galaxy Note 5 64GB Black' 'Motorola Moto G (3rd Gen) 16GB Black'
 'Alienware MacBook 4GB RAM Black' 'Samsung Galaxy S6 Edge 64GB Black'
 'Samsung Galaxy J7 16GB White' 'Xiaomi Redmi Note 4G 32GB White'
 'Samsung Galaxy Note 5 16GB Black' 'Samsung Galaxy Tab 8GB RAM Black']

 category
['electronics']

 subcategory
['Smartphones' 'Laptops' 'Tablets' 'Smart Watch' 'Audio'
 'TV & Entertainment']

 brand
['Samsung' 'OnePlus' 'Motorola' 'Alienware' 'Xiaomi' 'Apple' 'Garmin'
 'Audio-Technica' 'MSI' 'LG']

 customer_city
['Mumbai' 'Allahabad' 'Kolkata' 'Ludhiana' 'Delhi' 'Lucknow' 'Jaipur'
 'Bhubaneswar' 'Ahmedabad' 'Bengaluru']

 customer_state
['Maharashtra' 'Uttar Pradesh' 'West Bengal' 'Punjab' 'Delhi' 'Rajasthan'
 'Odisha' 'Gujarat' 'Karnataka' 'Kerala']

 customer_tier
['Metro' 'Rural' 'Tier2' 'Tier1']

 customer_spending_tier
['Premium' 'Standard' 'Budget']

 customer_age_group
['46-55' '26-35' '36-45' '18-25' 'Unknown' '55+']

 payment_method
['COD' 'Debit Card' 'Credit Card' 'Net Banking' 'UPI' 'Wallet' 'BNPL']

 delivery_type
['Standard' 'Same Day' 'Express']

 festival_name
['Republic Day Sale' 'No Festival' 'Valentine Sale' 'Holi Festival'
 'Summer Sale' 'Back to School' 'Prime Day' 'Amazon Great Indian Festival'
 'Diwali Sale']

 return_status
['Delivered' 'Returned' 'Cancelled']

###Data Validation Checks

In [44]:
print(df['payment_method'].value_counts())
print(df['payment_method'].unique())

payment_method
UPI            347551
COD            291875
Credit Card    155589
Debit Card     126565
Net Banking     58781
Wallet          20657
BNPL            18335
Name: count, dtype: int64
['COD' 'Debit Card' 'Credit Card' 'Net Banking' 'UPI' 'Wallet' 'BNPL']

In [45]:
print(df['festival_name'].value_counts())

festival_name
No Festival                     703046
Back to School                   77052
Diwali Sale                      75647
Amazon Great Indian Festival     48099
Summer Sale                      40591
Holi Festival                    35754
Republic Day Sale                18272
Valentine Sale                   12785
Prime Day                         8107
Name: count, dtype: int64

In [46]:
invalid_amounts = (
    abs(
        df['final_amount_inr']
        - (df['subtotal_inr'] + df['delivery_charges'])
    ) > 1
).sum()

print("Invalid amount records:", invalid_amounts)

Invalid amount records: 1

In [47]:
print("Month mismatches:",
      (df['order_month'] != df['order_date'].dt.month).sum())

print("Year mismatches:",
      (df['order_year'] != df['order_date'].dt.year).sum())

print("Quarter mismatches:",
      (df['order_quarter'] != df['order_date'].dt.quarter).sum())

Month mismatches: 0
Year mismatches: 0
Quarter mismatches: 0

###Duplicate Values Handling

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
dup_cols = ['customer_id', 'product_id', 'order_date', 'final_amount_inr']

df_dup = df[df.duplicated(subset=dup_cols, keep=False)]
print(df_dup.shape)

(10058, 34)

In [50]:
df.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.000000,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,electronics,Smartphones,OnePlus,54731.86,0.00,...,False,No Festival,4.500000,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,4.340115,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,electronics,Smartphones,Motorola,46625.88,0.00,...,False,No Festival,3.000000,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,electronics,Smartphones,OnePlus,54731.86,0.00,...,False,No Festival,4.000000,Delivered,1,2015,1,0.20,True,4.1

In [51]:
df_dup.sort_values(by=dup_cols).head(20)

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
503521,TXN_2020_00116597,2020-11-20,CUST_2015_00000020,PROD_001826,OnePlus Gaming Headset Premium,electronics,Audio,OnePlus,26420.31,0.00,...,False,No Festival,3.000000,Delivered,11,2020,4,0.35,True,4.6
530013,TXN_2020_00116597_DUP,2020-11-20,CUST_2015_00000020,PROD_001826,OnePlus Gaming Headset Premium,electronics,Audio,OnePlus,26420.31,0.00,...,False,No Festival,3.000000,Delivered,11,2020,4,0.35,True,4.6
1851,TXN_2015_00001852,2015-01-23,CUST_2015_00000037,PROD_000053,OnePlus OnePlus 2 32GB Black,electronics,Smartphones,OnePlus,102649.14,19.30,...,True,Republic Day Sale,5.000000,Delivered,1,2015,1,0.20,True,4.6
33077,TXN_2015_00001852_DUP,2015-01-23,CUST_2015_00000037,PROD_000053,OnePlus OnePlus 2 32GB Black,electronics,Smartphones,OnePlus,102649.14,19.30,...,True,Republic Day Sale,5.000000,Delivered,1,2015,1,0.20,True,4.6
507198,TXN_2020_00120274,2020-11-15,CUST_2015_00000046,PROD_000061,OnePlus OnePlus X 32GB White,electronics,Smartphones,OnePlus,102173.68,11.89,...,False,No Festival,4.340115,Delivered,11,2020,4,0.19,True,3.6
530460,TXN_2020_00120274_DUP,2020-11-15,CUST_2015_00000046,PROD_000061,OnePlus OnePlus X 32GB White,electronics,Smartphones,OnePlus,102173.68,11.89,...,False,No Festival,4.340115,Delivered,11,2020,4,0.19,True,3.6
149682,TXN_2017_00061243,2017-11-20,CUST_2015_00000099,PROD_000176,Xiaomi Mi 5 16GB Black,electronics,Smartphones,Xiaomi,46625.88,0.00,...,False,No Festival,4.340115,Delivered,11,2017,4,0.23,True,3.4
165730,TXN_2017_00061243_DUP,2017-11-20,CUST_2015_00000099,PROD_000176,Xiaomi Mi 5 16GB Black,electronics,Smartphones,Xiaomi,46625.88,0.00,...,False,No Festival,4.340115,Delivered,11,2017,4,0.23,True,3.4
439932,TXN_2020_00053008,2020-05-03,CUST_2015_00000122,PROD_000743,Realme Realme X50 Pro 64GB Black,electronics,Smartphones,Realme,42295.50,62.38,...,True,Summer Sale,4.500000,Delivered,5,2020,2,0.23,True,4.5
530402,TXN_2020_00053008_DUP,2020-05-03,CUST_2015_00000122,PROD_000743,Realme Realme X50 Pro 64GB Black,electronics,Smartphones,Realme,42295.50,62.38,...,True,Summer Sale,4.500000,Delivered,5,2020,2,0.23,True,4.5
496382,TXN_2020_00109458,2020-10-28,CUST_2015_00000134,PROD_000040,Samsung Galaxy Note 5 16GB White,electronics,Smartphones,Samsung,184502.49,57.79,...,True,Diwali Sale,4.340115,Delivered,10,2020,4,0.15,True,4.0
530563,TXN_2020_00109458_DUP,2020-10-28,CUST_2015_00000134,PROD_000040,Samsung Galaxy Note 5 16GB White,electronics,Smartphones,Samsung,184502.49,57.79,...,True,Diwali Sale,4.340115,Delivered,10,2020,4,0.15,True,4.0
919195,TXN_2023_00117709,2023-12-08,CUST_2015_00000167,PROD_000974,Samsung Galaxy S22 64GB Blue,electronics,Smartphones,Samsung,46625.88,0.00,...,False,No Festival,4.309013,Returned,12,2023,4,0.21,True,4.0
928433,TXN_2023_00117709_DUP,2023-12-08,CUST_2015_00000167,PROD_000974,Samsung Galaxy S22 64GB Blue,electronics,Smartphones,Samsung,46625.88,0.00,...,False,No Festival,4.309013,Returned,12,2023,4,0.21,True,4.0
284525,TXN_2019_00019206,2019-03-05,CUST_2015_00000229,PROD_001743,Realme Galaxy Tab 8GB RAM Silver,electronics,Tablets,Realme,59171.91,50.85,...,True,Holi Festival,4.340115,Delivered,3,2019,1,0.67,True,4.0
386463,TXN_2019_00019206_DUP,2019-03-05,CUST_2015_00000229,PROD_001743,Realme Galaxy Tab 8GB RAM Silver,electronics,Tablets,Realme,59171.91,50.85,...,True,Holi Festival,4.340115,Delivered,3,2019,1,0.67,True,4.0
204713,TXN_2018_00038889,2018-06-02,CUST_2015_00000237,PROD_000063,OnePlus OnePlus X 32GB Blue,electronics,Smartphones,OnePlus,83692.32,0.00,...,False,No Festival,4.500000,Delivered,6,2018,2,0.18,True,3.8
265068,TXN_2018_00038889_DUP,2018-06-02,CUST_2015_00000237,PROD_000063,OnePlus OnePlus X 32GB Blue,electronics,Smartphones,OnePlus,83692.32,0.00,...,False,No Festival,4.500000,Delivered,6,2018,2,0.18,True,3.8
798570,TXN_2022_00129744,2022-12-18,CUST_2015_00000260,PROD_000407,Xiaomi Redmi 5A 256GB Black,electronics,Smartphones,Xiaomi,46625.88,14.26,...,False,No Festival,4.000000,Delivered,12,2022,4,0.23,True,4.6
801142,TXN_2022_00129744_DUP,2022-12-18,CUST_2015_00000260,PROD_000407,Xiaomi Redmi 5A 256GB Black,electronics,Smartphones,Xiaomi,46625.88,14.26,...,False,No Festival,4.000000,Delivered,12,2022,4,0.23,True,4.6

In [53]:
df.drop_duplicates(inplace=True)

In [54]:
print("Shape after removing duplicates:", df.shape)
print("Remaining duplicates:", df.duplicated().sum())

Shape after removing duplicates: (1019353, 34)
Remaining duplicates: 0

###Outlier Detection & Handling

In [55]:
numeric_cols = [
    'original_price_inr',
    'discounted_price_inr',
    'final_amount_inr',
    'quantity',
    'delivery_days',
    'product_weight_kg',
    'customer_rating'
]

df[numeric_cols].skew().sort_values(ascending=False)

original_price_inr      35.638092
product_weight_kg        9.201437
final_amount_inr         3.007028
quantity                 2.070985
discounted_price_inr     1.757628
delivery_days            0.767552
customer_rating         -0.740711
dtype: float64

In [56]:
numeric_cols = [
    'original_price_inr',
    'discounted_price_inr',
    'final_amount_inr',
    'quantity',
    'delivery_days',
    'product_weight_kg',
    'customer_rating'
]

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    print(f"{col}: {outliers} outliers")

original_price_inr: 45181 outliers
discounted_price_inr: 47516 outliers
final_amount_inr: 61182 outliers
quantity: 203455 outliers
delivery_days: 1976 outliers
product_weight_kg: 251783 outliers
customer_rating: 37643 outliers

In [57]:
def flag_outliers_iqr(df, col):
    outlier_mask = pd.Series(False, index=df.index)

    for (sub, br), group in df.groupby(['subcategory', 'brand']):
        q1 = group[col].quantile(0.25)
        q3 = group[col].quantile(0.75)

        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        outlier_mask.loc[group.index] = (
            (group[col] < lower) |
            (group[col] > upper)
        )

    return outlier_mask

df['price_outlier_IQR'] = flag_outliers_iqr(df, 'original_price_inr')

In [58]:
def flag_outliers_sigma(df, col):
    outlier_mask = pd.Series(False, index=df.index)

    for (sub, br), group in df.groupby(['subcategory', 'brand']):

        mean = group[col].mean()
        std = group[col].std()

        if std == 0 or pd.isna(std):
            continue

        lower = mean - 3 * std
        upper = mean + 3 * std

        outlier_mask.loc[group.index] = (
            (group[col] < lower) |
            (group[col] > upper)
        )

    return outlier_mask

df['price_outlier_3sigma'] = flag_outliers_sigma(df, 'original_price_inr')

In [59]:
print("IQR Outliers:",
      df['price_outlier_IQR'].sum())

print("3-Sigma Outliers:",
      df['price_outlier_3sigma'].sum())

IQR Outliers: 15709
3-Sigma Outliers: 2515

In [60]:
df.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating,price_outlier_IQR,price_outlier_3sigma
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,electronics,Smartphones,Samsung,123614.29,27.91,...,5.000000,Delivered,1,2015,1,0.19,True,4.7,False,False
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,electronics,Smartphones,OnePlus,54731.86,0.00,...,4.500000,Delivered,1,2015,1,0.20,True,4.1,False,False
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,electronics,Smartphones,Samsung,97644.25,46.93,...,4.340115,Delivered,1,2015,1,0.17,True,3.3,False,False
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,electronics,Smartphones,Motorola,46625.88,0.00,...,3.000000,Delivered,1,2015,1,0.22,True,3.5,True,False
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,electronics,Smartphones,OnePlus,54731.86,0.00,...,4.000000,Delivered,1,2015,1,0.20,True,4.1,False,False

In [61]:
df.to_csv(r"D:\Amazon_EDA_Project\amazon_india_cleaned_data.csv", index=False)